# Generated by Django 3.1.1 on 2020-09-23 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEmpresa', models.CharField(max_length=255)),
                ('razaoSocial', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('endereço', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('dataCadastroEmp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=5)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
            ],
        ),
    ]
