# Generated by Django 3.1.1 on 2020-09-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_horarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='dataUpdateEm',
            new_name='dataUpdateEmp',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='horarios',
        ),
    ]
