# Generated by Django 3.1.1 on 2020-10-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200930_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='telefoneCliente',
            field=models.CharField(max_length=255, verbose_name='telefone'),
        ),
    ]
